default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: fd_alumni_hub_api_development
  url: <%= ENV["DATABASE_URL"] %>

test:
  <<: *default
  database: fd_alumni_hub_api_test
  url: <%= ENV["TEST_DATABASE_URL"] %>

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
